version: '2'

services:
  phoenix:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ../:/app
    depends_on:
      - postgres
  postgres:
    image: postgres:9.3.17-alpine
    volumes:
       - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
volumes:
    db_data: